// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportNoteToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportNoteToFile'](arg1, arg2);
}

export function ExportNotesZip(arg1) {
  return window['go']['main']['App']['ExportNotesZip'](arg1);
}

export function ImportNotesZip() {
  return window['go']['main']['App']['ImportNotesZip']();
}

export function OnDeleteNote() {
  return window['go']['main']['App']['OnDeleteNote']();
}

export function OnEmptyTrash() {
  return window['go']['main']['App']['OnEmptyTrash']();
}

export function OnFocusSearch() {
  return window['go']['main']['App']['OnFocusSearch']();
}

export function OnHelp(arg1) {
  return window['go']['main']['App']['OnHelp'](arg1);
}

export function OnNewFolder() {
  return window['go']['main']['App']['OnNewFolder']();
}

export function OnNewNote() {
  return window['go']['main']['App']['OnNewNote']();
}

export function OnOpenAbout() {
  return window['go']['main']['App']['OnOpenAbout']();
}

export function OnOpenPreferences() {
  return window['go']['main']['App']['OnOpenPreferences']();
}

export function OnSetTheme(arg1) {
  return window['go']['main']['App']['OnSetTheme'](arg1);
}

export function OnToggleNoteList() {
  return window['go']['main']['App']['OnToggleNoteList']();
}

export function OnToggleSidebar() {
  return window['go']['main']['App']['OnToggleSidebar']();
}

export function ReadBackupFile() {
  return window['go']['main']['App']['ReadBackupFile']();
}

export function SaveBackupFile(arg1) {
  return window['go']['main']['App']['SaveBackupFile'](arg1);
}

export function SetMenuRefs(arg1) {
  return window['go']['main']['App']['SetMenuRefs'](arg1);
}

export function UpdateMenuState(arg1) {
  return window['go']['main']['App']['UpdateMenuState'](arg1);
}
