// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {exporter} from '../models';
import {menu} from '../models';

export function ExportNoteToFile(arg1:string,arg2:string):Promise<void>;

export function ExportNotesZip(arg1:Array<exporter.NoteDTO>):Promise<void>;

export function ImportNotesZip():Promise<Array<exporter.ImportedNoteDTO>>;

export function OnCloseWindow():Promise<void>;

export function OnDeleteNote():Promise<void>;

export function OnEmptyTrash():Promise<void>;

export function OnExportAllMarkdown():Promise<void>;

export function OnExportBackup():Promise<void>;

export function OnExportCurrentNote():Promise<void>;

export function OnFocusSearch():Promise<void>;

export function OnHelp(arg1:string):Promise<void>;

export function OnImportBackup():Promise<void>;

export function OnImportMarkdown():Promise<void>;

export function OnNewFolder():Promise<void>;

export function OnNewNote():Promise<void>;

export function OnOpenAbout():Promise<void>;

export function OnOpenPreferences():Promise<void>;

export function OnSetTheme(arg1:string):Promise<void>;

export function OnToggleFullscreen():Promise<void>;

export function OnToggleNoteList():Promise<void>;

export function OnToggleSidebar():Promise<void>;

export function ReadBackupFile():Promise<string>;

export function SaveBackupFile(arg1:string):Promise<boolean>;

export function SetMenuRefs(arg1:menu.MenuRefs):Promise<void>;

export function UpdateMenuState(arg1:menu.MenuState):Promise<void>;
